### ISSUE TITLE
Main Scene: more details

### ISSUE THREAD

**Issue by Jesse1211** [Jesse1211/ECS-189L#24]
- [x] Character Movement
- [x] Camera Movement
- [x] Particle System
- [x] NPC
- [x] Expand tilemap & add more prefabs

**Comment by Kkyyy1115** [comment]
Camera can follow the player now. Character movement is done. I also made adjustments to the character movement data and camera movement boundary.

**Comment by Jesse1211** [comment]
Added Particle System
