### ISSUE TITLE
user interface

### ISSUE THREAD

**Issue by Jesse1211** [Jesse1211/ECS-189L#25]
- [x] Health bar
- [x] Dialog Text Issue #36 
- [x] Design the dialog background
- [x] Write the content in the dialog
- [x] #50

**Comment by Jesse1211** [comment]
Completed basic implementation of the health bar.

**Comment by Kkyyy1115** [comment]
Add death scene and heath bar https://github.com/Jesse1211/ECS-189L/tree/User-Interface

**Comment by Kkyyy1115** [comment]
Add death scene and health bar https://github.com/Jesse1211/ECS-189L/commit/1e69d898029ee4ff6e79623374c14666ed300b9a
