### ISSUE TITLE
Animation states

### ISSUE THREAD

**Issue by Jesse1211** [Jesse1211/ECS-189L#26]
- [x] Describe in below

**Comment by Mowon0303** [comment]
- [x] Built animation for battle scene characters including elk, fox, crow, and rats. 
- [x] Made the character stand on the platform instead of falling to the bottom.
- [x] Built those characters' animations including Fanboy and gunslinger.

**Comment by Mowon0303** [comment]
I have built those characters' animations including Fanboy and gunslinger.

**Comment by Jesse1211** [comment]
Completed https://github.com/Jesse1211/ECS-189L/commit/3d285dc181c0fcb4e6e2d469ce32c6830a070ab9. Close Issue #26.
