### ISSUE TITLE
Main character animator logic & imp

### ISSUE THREAD

**Issue by Jesse1211** [Jesse1211/ECS-189L#37]
main character - little girl
- [x] Player control: keyboard usage
- [x] Animator states' requirements
- [x] Implement to animator

**Comment by xwang0908** [comment]
Left: A. left arrow; Right: D, right arrow; Jump: space, up arrow, W

Idle1: walking in main scene (the attack disabled in main scene)
- Fall: movement direction.y decreases & off the ground
- Run (speed > constant number)
- Transition (collect items (click M))

Dodge: S; stab: N; Gunattack: B; 
Idle2: walking in battle scene
- Dodge, stab, gunattack are detected by using the trigger in animator 
- Hit: when the enemy hits player
- Death: when HP drops to 0 or lower


Add-on: 
- brawFall: distinguish from Fall
- backDodge: distinguish from dodge
- specialJump: distinguish from jump (might be developed to ult)

**Comment by Jesse1211** [comment]
Error: fix controller decouple issue. Need to be fixed;
Implement the explanation listed above;

**Comment by Jesse1211** [comment]
Fix error: update new player controller https://github.com/Jesse1211/ECS-189L/commit/2d24aef790d1b375e19ef8352711b34867d5e2bf

**Comment by xwang0908** [comment]
Please change Gunattack to J and B for bag open and close.
